// Synthetic demo data only. No real retailer-confidential or employee data.
export async function seed(sql) {
  for (const table of ["market_playbooks","pocket_guide_entries","huddle_briefings","visit_assignments","store_visits","route_stops","routes","key_account_agreements","store_product_performance","products","stores","retail_accounts","markets"]) await sql.unsafe(`TRUNCATE TABLE public.${table} CASCADE`)

  await sql`INSERT INTO markets (id,name,country_code,currency) VALUES ('ch','Switzerland','CH','CHF'),('at','Austria','AT','EUR'),('de-south','Germany South','DE','EUR')`
  await sql`INSERT INTO retail_accounts (id,market_id,name,channel,tier) VALUES ('coop-ch','ch','Coop','grocery','key_account'),('migros-ch','ch','Migros','grocery','key_account'),('avec-ch','ch','avec','convenience','strategic'),('spar-at','at','SPAR Austria','grocery','key_account')`
  await sql`INSERT INTO stores (id,account_id,name,city,format,latitude,longitude,priority_score) VALUES ('coop-zrh-hb','coop-ch','Coop Zürich HB','Zürich','travel',47.3782,8.5402,94),('coop-oerlikon','coop-ch','Coop Oerlikon','Zürich','supermarket',47.4108,8.5447,82),('migros-limmat','migros-ch','Migros Limmatplatz','Zürich','supermarket',47.3841,8.5314,88),('avec-stadelhofen','avec-ch','avec Zürich Stadelhofen','Zürich','convenience',47.3661,8.5487,91),('migros-bern','migros-ch','Migros Bern Marktgasse','Bern','supermarket',46.9484,7.4474,73),('spar-vienna','spar-at','SPAR Wien Mitte','Wien','supermarket',48.2068,16.3853,79)`
  await sql`INSERT INTO products (id,name,category,pack_size,priority) VALUES ('rb-250','Red Bull Energy Drink','Core','250 ml',true),('rb-sf-250','Red Bull Sugarfree','Sugarfree','250 ml',true),('rb-red-250','Red Bull Red Edition','Editions','250 ml',true),('rb-sea-250','Red Bull Sea Blue Edition','Editions','250 ml',false)`
  await sql`INSERT INTO store_product_performance (store_id,product_id,week_start,units_sold,sales_trend_pct,on_shelf_availability_pct,facings,target_facings,planogram_compliant) VALUES
    ('coop-zrh-hb','rb-250','2026-07-20',412,-8,84,3,5,false),('coop-zrh-hb','rb-sf-250','2026-07-20',218,12,96,2,3,false),('coop-zrh-hb','rb-red-250','2026-07-20',164,-15,78,1,3,false),
    ('coop-oerlikon','rb-250','2026-07-20',301,4,97,5,5,true),('coop-oerlikon','rb-sf-250','2026-07-20',140,-3,88,2,3,false),('migros-limmat','rb-250','2026-07-20',355,7,92,4,5,false),('migros-limmat','rb-red-250','2026-07-20',132,18,90,2,3,false),
    ('avec-stadelhofen','rb-250','2026-07-20',498,21,98,6,6,true),('avec-stadelhofen','rb-sf-250','2026-07-20',245,16,94,3,3,true),('migros-bern','rb-250','2026-07-20',280,2,96,5,5,true)`
  await sql`INSERT INTO key_account_agreements (id,account_id,title,clause_type,product_id,required_facings,valid_from,valid_to,status) VALUES ('agr-coop-core','coop-ch','Coop Core Visibility 2026','minimum_facings','rb-250',5,'2026-01-01','2026-12-31','active'),('agr-coop-red','coop-ch','Summer Editions Visibility','minimum_facings','rb-red-250',3,'2026-06-01','2026-08-31','active'),('agr-migros-sf','migros-ch','Sugarfree Growth Block','minimum_facings','rb-sf-250',3,'2026-04-01','2026-12-31','active')`
  await sql`INSERT INTO routes (id,market_id,owner_name,route_date,status) VALUES ('route-ch-zrh-0721','ch','Alex Meyer','2026-07-21','planned')`
  await sql`INSERT INTO route_stops (route_id,store_id,stop_order,planned_at,objective) VALUES ('route-ch-zrh-0721','coop-zrh-hb',1,'08:30','Recover core availability and summer visibility'),('route-ch-zrh-0721','avec-stadelhofen',2,'10:00','Protect strong execution and secure secondary placement'),('route-ch-zrh-0721','migros-limmat',3,'11:30','Close priority-facing gaps'),('route-ch-zrh-0721','coop-oerlikon',4,'14:00','Recover Sugarfree availability')`
  await sql`INSERT INTO store_visits (id,store_id,route_id,visited_at,status,perfect_store_score,notes) VALUES ('visit-coop-zrh-prev','coop-zrh-hb',NULL,'2026-07-14T09:10:00Z','completed',68,'Core cooler gap and Red Edition under-faced.'),('visit-avec-prev','avec-stadelhofen',NULL,'2026-07-15T10:00:00Z','completed',94,'Strong execution; secondary placement opportunity.'),('visit-coop-zrh-today','coop-zrh-hb','route-ch-zrh-0721',NULL,'planned',NULL,NULL)`
  await sql`INSERT INTO visit_assignments (id,visit_id,store_id,product_id,title,rationale,priority,status,due_at) VALUES ('asg-core-osa','visit-coop-zrh-today','coop-zrh-hb','rb-250','Restore core cooler availability','OSA is 84% and agreement requires five facings.','high','open','2026-07-21T10:00:00Z'),('asg-red-facing','visit-coop-zrh-today','coop-zrh-hb','rb-red-250','Build Red Edition to three facings','OSA is 78%; active summer clause requires three facings.','high','open','2026-07-21T10:00:00Z'),('asg-avec-display',NULL,'avec-stadelhofen','rb-250','Pitch secondary checkout placement','Execution is strong and sales trend is +21%.','medium','open','2026-07-21T12:00:00Z')`
  await sql`INSERT INTO huddle_briefings (id,market_id,briefing_date,title,priorities,message) VALUES ('huddle-ch-0721','ch','2026-07-21','Swiss Market Morning Huddle',ARRAY['Recover priority-SKU OSA below 90%','Execute active summer-edition facing clauses','Protect high-velocity travel outlets'],'Lead with availability, verify back stock, and leave every task with photographic evidence.')`
  await sql`INSERT INTO pocket_guide_entries (id,topic,title,body,tags) VALUES ('pg-osa-01','availability','Low OSA with adequate facings','Check shelf and cooler stock, verify back stock, correct replenishment, then confirm the shelf label and scan path before negotiating more space.',ARRAY['OSA','replenishment']),('pg-facing-01','visibility','Closing a facing gap','Reference the active planogram or account clause, quantify the gap, propose the smallest compliant reset, and capture completion evidence.',ARRAY['facings','planogram','agreement'])`
  await sql`INSERT INTO market_playbooks (id,market_id,name,version,status,rules) VALUES ('pb-ch-recovery-v1','ch','Priority SKU Recovery',1,'published','{"availabilityBelow":90,"prioritySkuOnly":true,"missingTargetFacings":true}'::jsonb)`
  return { markets: 3, retail_accounts: 4, stores: 6, products: 4, routes: 1, synthetic: true }
}
