-- Synthetic Red Bull field-sales demo schema. Idempotent.
CREATE TABLE IF NOT EXISTS public.markets (id text PRIMARY KEY, name text NOT NULL, country_code text NOT NULL, currency text NOT NULL);
CREATE TABLE IF NOT EXISTS public.retail_accounts (id text PRIMARY KEY, market_id text REFERENCES public.markets(id), name text NOT NULL, channel text NOT NULL, tier text NOT NULL);
CREATE TABLE IF NOT EXISTS public.stores (id text PRIMARY KEY, account_id text REFERENCES public.retail_accounts(id), name text NOT NULL, city text NOT NULL, format text NOT NULL, latitude numeric, longitude numeric, priority_score numeric NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS public.products (id text PRIMARY KEY, name text NOT NULL, category text NOT NULL, pack_size text NOT NULL, priority boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS public.store_product_performance (store_id text REFERENCES public.stores(id), product_id text REFERENCES public.products(id), week_start date NOT NULL, units_sold integer NOT NULL, sales_trend_pct numeric, on_shelf_availability_pct numeric, facings integer, target_facings integer, planogram_compliant boolean, PRIMARY KEY (store_id, product_id, week_start));
CREATE TABLE IF NOT EXISTS public.key_account_agreements (id text PRIMARY KEY, account_id text REFERENCES public.retail_accounts(id), title text NOT NULL, clause_type text NOT NULL, product_id text REFERENCES public.products(id), required_facings integer, valid_from date NOT NULL, valid_to date NOT NULL, status text NOT NULL);
CREATE TABLE IF NOT EXISTS public.routes (id text PRIMARY KEY, market_id text REFERENCES public.markets(id), owner_name text NOT NULL, route_date date NOT NULL, status text NOT NULL);
CREATE TABLE IF NOT EXISTS public.route_stops (route_id text REFERENCES public.routes(id), store_id text REFERENCES public.stores(id), stop_order integer NOT NULL, planned_at time, objective text, PRIMARY KEY (route_id, store_id));
CREATE TABLE IF NOT EXISTS public.store_visits (id text PRIMARY KEY, store_id text REFERENCES public.stores(id), route_id text REFERENCES public.routes(id), visited_at timestamptz, status text NOT NULL, perfect_store_score numeric, notes text);
CREATE TABLE IF NOT EXISTS public.visit_assignments (id text PRIMARY KEY, visit_id text REFERENCES public.store_visits(id), store_id text REFERENCES public.stores(id), product_id text REFERENCES public.products(id), title text NOT NULL, rationale text NOT NULL, priority text NOT NULL, status text NOT NULL DEFAULT 'open', due_at timestamptz, completed_at timestamptz);
CREATE TABLE IF NOT EXISTS public.huddle_briefings (id text PRIMARY KEY, market_id text REFERENCES public.markets(id), briefing_date date NOT NULL, title text NOT NULL, priorities text[] NOT NULL, message text NOT NULL);
CREATE TABLE IF NOT EXISTS public.pocket_guide_entries (id text PRIMARY KEY, topic text NOT NULL, title text NOT NULL, body text NOT NULL, tags text[] NOT NULL);
CREATE TABLE IF NOT EXISTS public.market_playbooks (id text PRIMARY KEY, market_id text REFERENCES public.markets(id), name text NOT NULL, version integer NOT NULL, status text NOT NULL, rules jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz);
CREATE INDEX IF NOT EXISTS stores_account_idx ON public.stores(account_id);
CREATE INDEX IF NOT EXISTS performance_store_idx ON public.store_product_performance(store_id, week_start DESC);
CREATE INDEX IF NOT EXISTS assignments_store_idx ON public.visit_assignments(store_id, status);
